command_timeout = 750

palette = "mine"

[palettes.mine]
limegreen = '#32CD32'

[battery]
disabled = true
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[c]
disabled = true
commands = [["$CC", "--version"], ["clang", "--version"], ["gcc", "--version"]]
format = 'via [$symbol($name( $version)) ]($style)'

[character]
success_symbol = "[â²](limegreen)"
error_symbol = "[â²](bold red)"

[cmd_duration]
disabled = true

[dotnet]
disabled = true

[erlang]
symbol = "â“” "

[git_branch]
disabled = false

[git_status]
disabled = false

[nodejs]
symbol = "[â¬¢](bold green) "

[package]
disabled = true

[pulumi]
symbol = "ğŸ§Š "

[python]
python_binary = ["py"]
detect_files = []
detect_folders = [".venv"]

[typst]
symbol = "t "
