command_timeout = 750

palette = "mine"

[palettes.mine]
limegreen = '#32CD32'

[battery]
disabled = true
full_symbol = "‚Ä¢ "
charging_symbol = "‚á° "
discharging_symbol = "‚á£ "
unknown_symbol = "‚ùì "
empty_symbol = "‚ùó "

[c]
disabled = true
commands = [["$CC", "--version"], ["clang", "--version"], ["gcc", "--version"]]
format = 'via [$symbol($name( $version)) ]($style)'

[character]
success_symbol = "[‚û≤](limegreen)"
error_symbol = "[‚úó](bold red)"

[directory]
truncation_length = 2
truncation_symbol = "‚Ä¶/"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[cmd_duration]
disabled = true

[dotnet]
disabled = true

[erlang]
symbol = "‚ìî "

[git_branch]
disabled = false

[git_status]
disabled = false

[nodejs]
symbol = "[‚¨¢](bold green) "

[package]
disabled = true

[pulumi]
symbol = "üßä "

[python]
python_binary = ["py"]
detect_files = []
detect_folders = [".venv"]

[typst]
symbol = "t "
